language: python
python:
  - "3.6"
  
# command to install dependencies
install:
#- pip install -r requirements.txt
script: true
  - nosetests --with-coverage --coverage report
# command to run tests
script:
  - python cal.py

deploy:
  provider: heroku
  api_key:
    secure: d430b880-87cd-4896-9789-4c654b08008e
  app: testcd00457019
  on:
    repo: Junghc/test_ci
  #Setting your heroku Procfile here!!!
  run:
    "web: gunicorn app_run:app"    
