language: python
python:
   - "3.6"
  
# command to install dependencies
install:
#- pip install -r requirements.txt
script:true
   - nosetests --with-coverage --coverage report
# command to run tests
script:
   - python cal.py
